#!/usr/bin/env bash
# =============================================================================
# Script Name: build.sh
# Description: Generate every derived artifact in this repo from the source
#              markdown — AGENTS.md, the Claude Code symlink, the Ollama
#              Modelfile, and the conventions.md rollup.
# Author: Juan Garcia (arpatek)
# Created: 2026-09-18
# Version: 1.0
# =============================================================================

if ((BASH_VERSINFO[0] < 4)); then
  printf "build.sh requires bash 4 or higher (detected: %s)\n" "$BASH_VERSION" >&2
  exit 1
fi

set -eo pipefail

trap 'printf "\033[33m[\033[31m!\033[33m]\033[0m build.sh failed at line %s\n" "$LINENO" >&2' ERR

# ──[ Decorators ]─────────────────────────────────────────────────────────────
# lib.sh is the canonical home for these; fall back so this repo stands alone.

if [[ -r "${LIB_SH:-$HOME/.local/lib/lib.sh}" ]]; then
  # shellcheck source=/dev/null
  source "${LIB_SH:-$HOME/.local/lib/lib.sh}"
else
  BANNER()   { printf "\033[33m[\033[35m^\033[33m]\033[0m"; }
  PLUS()     { printf "\033[33m[\033[32m+\033[33m]\033[0m"; }
  COMPLETE() { printf "\033[33m[\033[34m*\033[33m]\033[0m"; }
  FAILED()   { printf "\033[33m[\033[31m!\033[33m]\033[0m"; }
  LAMBDA()   { printf "\033[33m[\033[38;2;121;190;154mλ\033[33m]\033[0m"; }
fi

# ──[ Configuration ]──────────────────────────────────────────────────────────

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
build_dir="$script_dir/build"
model_base="${OLLAMA_BASE_MODEL:-qwen3:8b}"

readonly script_dir build_dir model_base

# ──[ Functions ]──────────────────────────────────────────────────────────────

usage() {
  cat <<'USAGE'
Usage: build.sh [OPTIONS]

Generates every derived artifact from the source markdown files.

Options:
  -o, --output DIR    Write AGENTS.md and CLAUDE.md here (default: ./build)
  -m, --model NAME    Base model for the Modelfile FROM line (default: qwen3:8b)
  -c, --check         Verify artifacts are current; exit 1 if stale. No writes.
  -h, --help          Show this message

Sources:                          Generated:
  soul.md                           build/AGENTS.md      (soul + style + context)
  style.md                          build/CLAUDE.md      (symlink -> AGENTS.md)
  context.md                        Modelfile            (everything, baked)
  skills/*/SKILL.md                 conventions.md       (readable rollup)
USAGE
}

# Concatenate the always-loaded persona files. Conventions are deliberately
# absent: Claude Code loads those as skills, on relevance rather than on boot.
compose_agents() {
  local f
  for f in soul.md style.md context.md; do
    cat "$script_dir/$f"
    printf '\n---\n\n'
  done
}

# The rollup exists so the repo stays readable on a forge. skills/ is the
# source of truth; this file is generated from it and should never be edited.
compose_conventions() {
  local skill body
  printf '# arpatek — code conventions\n\n'
  printf '<!-- Generated by build.sh from skills/. Do not edit. -->\n\n'
  # Backticks below are markdown code spans, not shell expansions.
  # shellcheck disable=SC2016
  printf 'Voice and interaction rules live in `style.md`. Each section below is\n'
  # shellcheck disable=SC2016
  printf 'also a Claude Code skill under `skills/`, loaded on relevance.\n\n---\n\n'
  for skill in bash python config git; do
    body="$script_dir/skills/${skill}-conventions/SKILL.md"
    [[ -r "$body" ]] || continue
    # awk, not sed: BSD sed rejects `q` inside braces, and this runs on macOS too.
    awk 'NR==1 && /^---$/ {fm=1; next} fm && /^---$/ {fm=0; next} !fm' "$body" |
      awk 'NF {found=1} found' |
      awk '/^#/ {sub(/^#/, "##")} 1'
    printf '\n---\n\n'
  done
}

# Ollama has no skill mechanism, so the local model gets everything baked in.
compose_modelfile() {
  printf 'FROM %s\n\n' "$model_base"
  printf '# Generated by build.sh — do not edit. Edit the source markdown instead.\n'
  printf '# To rebuild: ./build.sh && ollama create arpatek -f Modelfile\n\n'
  printf 'SYSTEM """\n'
  cat "$script_dir/soul.md" "$script_dir/style.md" "$script_dir/conventions.md" "$script_dir/context.md"
  printf '"""\n\n'
  printf 'PARAMETER temperature 0.7\n'
  printf 'PARAMETER num_ctx 8192\n\n'
  printf '# Few-shot calibration — show the model what good looks like\n'
  cat "$script_dir/calibration.msg"
}

write_artifact() {
  local path="$1" content="$2"
  if [[ -f "$path" ]] && [[ "$(cat "$path")" == "$content" ]]; then
    printf "%s %s unchanged\n" "$(COMPLETE)" "${path#"$script_dir"/}"
    return 0
  fi
  printf '%s' "$content" >"$path"
  printf "%s wrote %s\n" "$(PLUS)" "${path#"$script_dir"/}"
}

check_artifact() {
  local path="$1" content="$2"
  if [[ ! -f "$path" ]] || [[ "$(cat "$path")" != "$content" ]]; then
    printf "%s %s is stale — run ./build.sh\n" "$(FAILED)" "${path#"$script_dir"/}" >&2
    return 1
  fi
  printf "%s %s current\n" "$(COMPLETE)" "${path#"$script_dir"/}"
}

# ──[ Argument parsing ]───────────────────────────────────────────────────────

check_only=0
out_dir="$build_dir"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -o | --output)
      out_dir="$2"
      shift 2
      ;;
    -m | --model)
      model_base="$2"
      shift 2
      ;;
    -c | --check)
      check_only=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      printf "%s unknown option: %s\n" "$(FAILED)" "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

# ──[ Main ]───────────────────────────────────────────────────────────────────

printf "%s Building arpatek persona artifacts\n" "$(BANNER)"

conventions_out="$(compose_conventions)"
agents_out="$(compose_agents)"

if ((check_only)); then
  rc=0
  check_artifact "$script_dir/conventions.md" "$conventions_out" || rc=1
  check_artifact "$out_dir/AGENTS.md" "$agents_out" || rc=1
  check_artifact "$script_dir/Modelfile" "$(compose_modelfile)" || rc=1
  exit "$rc"
fi

mkdir -p "$out_dir"
write_artifact "$script_dir/conventions.md" "$conventions_out"
write_artifact "$out_dir/AGENTS.md" "$agents_out"

# Composed after the rollup lands: the Modelfile bakes conventions.md verbatim.
write_artifact "$script_dir/Modelfile" "$(compose_modelfile)"

# Claude Code reads CLAUDE.md, not AGENTS.md — this is the documented bridge.
ln -sf AGENTS.md "$out_dir/CLAUDE.md"
printf "%s linked %s -> AGENTS.md\n" "$(PLUS)" "${out_dir#"$script_dir"/}/CLAUDE.md"

printf "%s %s skills, %s words in the always-loaded config\n" \
  "$(COMPLETE)" \
  "$(find "$script_dir/skills" -name SKILL.md | wc -l | tr -d ' ')" \
  "$(printf '%s' "$agents_out" | wc -w | tr -d ' ')"

printf "%s install: ln -sf %s ~/.claude/CLAUDE.md\n" "$(LAMBDA)" "$out_dir/AGENTS.md"
